# Generated by Django 3.2 on 2021-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mids", "0002_start_end_dates_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="date_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="sender_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
